name: chucknorris
description: API-based joke retrieval package with simple request methods. Add some humor to your project with ease.
version: 1.0.0
repository: https://github.com/zTomz/Chucknorris

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  http: ^0.13.5
